version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: auth-service
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE} # Updated for MySQL
      PORT: ${PORT}
    depends_on:
      db:
        condition: service_healthy # Ensure it waits for the DB to be healthy
    restart: unless-stopped
    command: ['dumb-init', '/bin/sh', '-c', 'pnpm run dev']
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p',
          'root'
        ]
      interval: 5s
      timeout: 2s
      retries: 20
